site_name: RPG Archaeology

theme:
  name: material
  logo: assets/images/common/logo.png
  favicon: assets/images/common/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro
  features:
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: es
          default: true
          name: Español
          build: true

        - locale: en
          name: English
          build: true
          nav_translations:
            Inicio: Home
            Orígenes: Origins
            Influencias: Influences
            Autopsias: Autopsies

nav:
  - Inicio: index.md

  - Orígenes:
      - Influencias: influences.md
      - The Twin Cities School: twin_cities_school.md
      - Blackmoor: blackmoor.md
      - Chainmail: chainmail.md
      - "Dungeons & Dragons — Arneson y Gygax": dnd_history.md
      - CRPG Origins: crpg_origins.md

  - Autopsias:
      - "Wizardry I — Proving Grounds of the Mad Overlord": games/wizardry_1.md
      - "Dark Heart of Uukrul: Crónica arqueológica": games/uukrul_archaeological_chronicle.md
      - "Dark Heart of Uukrul: Informe técnico": games/uukrul_technical_sheet.md
      - "Bloodwych (1989)": games/bloodwych.md
      - "Unlimited Adventures (1993)": games/frua_dungeon_craft_authoring_archaeology.md
