site_name: RPG Archaeology

nav:
  - Inicio: index.md

  - Orígenes:
      - Influencias: influences.md
      - The Twin Cities School: The Twin Cities School — El laboratorio antes de D&D.md
      - Blackmoor: blackmoore.md
      - Chainmail: chainmail.md
      - "Dungeons & Dragons — Arneson y Gygax": Arnenson y Gygax La hisoria de D&D.md
      - CRPG Origins: crpg_origins.md
   
  - Autopsias:
      - "Wizardry I — Proving Grounds of the Mad Overlord": games/wizardry_1.md
      - "Dark Heart of Uukrul: Cronica arqueologica": games\Dark Heart of Uukrul_cronica_arqueologica.md
      - "Dark Heart of Uukrul: Informe Tecnico": games\Dark Heart of Uukrul_technical_sheet.md
      - "Bloodwych (1989)": games\Bloodwych (1989) — RPG Archaeology.md